# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mypn', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('venderpn', models.CharField(max_length=30)),
                ('datasheet', models.FileField(upload_to=b'')),
                ('refdesign', models.URLField()),
                ('refcode', models.FileField(upload_to=b'')),
                ('refsch', models.FileField(upload_to=b'')),
                ('state', models.NullBooleanField()),
            ],
        ),
    ]
