# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mypn', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(choices=[(1, 'anolog'), (2, 'logic'), (3, 'power'), (4, 'storage'), (5, 'other')], max_length=30, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('venderpn', models.CharField(max_length=30, null=True)),
                ('datasheet', models.FileField(null=True, upload_to='datasheet/')),
                ('refdesign', models.URLField()),
                ('refcode', models.FileField(upload_to='refcode/')),
                ('refsch', models.FileField(upload_to='resch/')),
                ('state', models.NullBooleanField()),
                ('time', models.TimeField(auto_now=True, null=True)),
            ],
        ),
    ]
