# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ic',
            name='datasheet',
            field=models.FileField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='ic',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ic',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ic',
            name='value',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ic',
            name='venderpn',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
