# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ic',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
