# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0002_auto_20161011_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ic',
            name='datasheet',
            field=models.FileField(null=True, upload_to='datasheet/'),
        ),
    ]
