# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0003_auto_20161017_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ic',
            name='mypn',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
