# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0003_auto_20161011_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ic',
            name='refcode',
            field=models.FileField(upload_to='refcode/'),
        ),
        migrations.AlterField(
            model_name='ic',
            name='refsch',
            field=models.FileField(upload_to='resch/'),
        ),
        migrations.AlterField(
            model_name='ic',
            name='type',
            field=models.CharField(choices=[(1, 'anolog'), (2, 'logic'), (3, 'power'), (4, 'storage'), (5, 'other')], max_length=30, null=True),
        ),
    ]
